name: thatkeith
favicon: null
layout_spectrum: 0.74852
typography_spectrum: 0.9746756877284497
title: Tester
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cab18d'
    - '#462c1e'
    - '#9a826c'
    - '#806654'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
